version: '3.8'
services:
  mongo:
    image: mongo:8.0
    container_name: tangent.mongo
    ports:
      - '27017:27017'
    command: ['mongod', '--replSet', 'rs0', '--bind_ip_all']
    volumes:
      # This mounts the replica set initialization script.
      - ./init-replica.sh:/docker-entrypoint-initdb.d/init-replica.sh:ro

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.2
    container_name: tangent.elasticsearch
    environment:
      - node.name=es01
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - '9200:9200'
      - '9300:9300'
